GESTORES = ['IVAN DE MEDEIROS DUARTE FILHO', 'EDMILSON FIRMINO DA SILVA', 'JEAZI CAMPOS DE AMORIM', 
            'EDIVAL SOARES DA SILVA', 'EDUARDO SILVINO DA SILVA', 'ALAN FARIAS ANTONINO', 
            'ADILSON FERREIRA MOURA', 'JOSE AGUINALDO FERNANDES DA SI', 'JOSE ANTONIO DA SILVA', 
            'JOSE FABIO DA SILVA RAMALHO', 'LUCAS CARVALHO DE OLIVEIRA', 'PETRONIO CARLOS SANTOS DO NASCIMENTO',
            'TIAGO RANGEL DE SOUSA SILVA', 'WILLIAM LUIZ CARVALHO', 'ESDRAS VENICIUS DE ANDRADE MACEDO']